---
title: "ESM 203 Assignment 4"
author: "Robert Saldivar"
date: "December 5, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Part 0 Load Packages and read in data
```{r, include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)

flooding_probability <- read_csv("Probability of flooding.csv")
flood_risk_2050 <- read_csv("Flood_Risk_2050.csv")
```


Part 1 Creating A Statistical Model
```{r sample random number generator, include=FALSE}

x <- rnorm(1000, mean = 0, sd = 1) %>%
  as.data.frame()

```

```{r}
#Creating a sample of tide ranges

tide_range <- rnorm(10000, mean = 2.5, sd = 3) %>%
  as.data.frame

colnames(tide_range) <- c("tide_range")
#Creating a random set of numbers for tide ranges around a mean of 2.5 and a sd of 3


```

```{r}
#inital data exploration

tide_range_hist <- ggplot(tide_range, aes(x=tide_range)) +
  geom_histogram(bins=43, fill = "blue", color="black") +
  theme_classic()
tide_range_hist #creating a histogram to view normal distribution of tide range

tide_range_qq <- ggplot(tide_range, aes(sample=tide_range)) +
  geom_qq()
tide_range_qq #creating a qq plot to view normal distribution of tide range

```


```{r}
# Counting the amount of floods and proportion under normal conditions

tide_range_flood <- tide_range %>%
  mutate(Flood = ifelse(tide_range > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

Flood_Prop <- round(prop.table(as.matrix(tide_range_flood), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

#The Risk of flood under normal conditions is 4.8%

```

```{r}
# Counting the amount of floods and proportion under normal conditions at high tide

tide_range_high <- rnorm(10000, mean = 5, sd = 3) %>%
  as.data.frame

colnames(tide_range_high) <- c("tide_range_high")

tide_range_flood_high <- tide_range_high %>%
  mutate(Flood = ifelse(tide_range_high > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

Flood_Prop_high <- round(prop.table(as.matrix(tide_range_flood_high), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

#The Risk of flood under normal conditions at high tide is 19.8%

```

```{r}
# Counting the amount of floods and proportion under normal conditions at low tide

tide_range_low <- rnorm(10000, mean = 0, sd = 3) %>%
  as.data.frame

colnames(tide_range_low) <- c("tide_range_low")

tide_range_flood_low <- tide_range_low %>%
  mutate(Flood = ifelse(tide_range_low > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

Flood_Prop_low <- round(prop.table(as.matrix(tide_range_flood_low), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

#The Risk of flood under normal conditions at low tide is 0.6%
```


```{r}
# Counting the amount of floods and proportions with a storm surge of 1m in the middle of high and low tide

storm_surge1_0 <- rnorm(10000, mean = 3.5, sd = 3) %>%
  as.data.frame

colnames(storm_surge1_0) <- c("storm_surge1_0")

storm_surge1_0flood <- storm_surge1_0 %>%
  mutate(Flood = ifelse(storm_surge1_0 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n)

storm_surge1_0prop <- round(prop.table(as.matrix(storm_surge1_0flood), 1), 3)

#there is a 8.7% chance of flooding under these conditions

```

```{r}
# Counting the amount of floods and proportions with a storm surge of 1m at high tide

storm_surge1_high <- rnorm(10000, mean = 6, sd = 3) %>%
  as.data.frame

colnames(storm_surge1_high) <- c("storm_surge1_high")

storm_surge1_highflood <- storm_surge1_high %>%
  mutate(Flood = ifelse(storm_surge1_high > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n)

storm_surge1_highprop <- round(prop.table(as.matrix(storm_surge1_highflood), 1), 3)

#there is a 30.9 percent chance of flooding under these conditions
```

```{r}
# Counting the amount of floods and proportions with a storm surge of 1m at low tide

storm_surge1_low <- rnorm(10000, mean = 1, sd = 3) %>%
  as.data.frame

colnames(storm_surge1_low) <- c("storm_surge1_low")

storm_surge1_lowflood <- storm_surge1_low %>%
  mutate(Flood = ifelse(storm_surge1_low > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n)

storm_surge1_lowprop <- round(prop.table(as.matrix(storm_surge1_lowflood), 1), 3)

#there is a 1.6% chance of flooding under these conditions
```

```{r}
# Counting the amount of floods and proportions with a storm surge of 2m

storm_surge2_0 <- rnorm(10000, mean = 4.5, sd = 3) %>%
  as.data.frame

colnames(storm_surge2_0) <- c("storm_surge2_0")

storm_surge2_0flood <- storm_surge2_0 %>%
  mutate(Flood = ifelse(storm_surge2_0 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n)

storm_surge2_0prop <- round(prop.table(as.matrix(storm_surge2_0flood), 1), 3)

#there is a 15.4% chance of flooding under these conditions
```

```{r}
# Counting the amount of floods and proportions with a storm surge of 2m at high tide

storm_surge2_high <- rnorm(10000, mean = 7, sd = 3) %>%
  as.data.frame

colnames(storm_surge2_high) <- c("storm_surge2_high")

storm_surge2_highflood <- storm_surge2_high %>%
  mutate(Flood = ifelse(storm_surge2_high > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n)

storm_surge2_highprop <- round(prop.table(as.matrix(storm_surge2_highflood), 1), 3)

#there is a 43.1% chance of flooding under these conditions
```

```{r}
# Counting the amount of floods and proportions with a storm surge of 2m at low tide

storm_surge2_low <- rnorm(10000, mean = 2, sd = 3) %>%
  as.data.frame

colnames(storm_surge2_low) <- c("storm_surge2_low")

storm_surge2_lowflood <- storm_surge2_low %>%
  mutate(Flood = ifelse(storm_surge2_low > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n)

storm_surge2_lowprop <- round(prop.table(as.matrix(storm_surge2_lowflood), 1), 3)

#there is a 3.2% chance of flooding under these conditions
```


```{r}
# Counting the amount of floods and proportions with a storm surge of 3m between high and low tide

storm_surge3_0 <- rnorm(10000, mean = 5.5, sd = 3) %>%
  as.data.frame

colnames(storm_surge3_0) <- c("storm_surge3_0")

storm_surge3_0flood <- storm_surge3_0 %>%
  mutate(Flood = ifelse(storm_surge3_0 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n)

storm_surge3_0prop <- round(prop.table(as.matrix(storm_surge3_0flood), 1), 3)

#there is a 25% chance of flooding under these conditions
```

```{r}
# Counting the amount of floods and proportions with a storm surge of 3m at high tide

storm_surge3_high <- rnorm(10000, mean = 8, sd = 3) %>%
  as.data.frame

colnames(storm_surge3_high) <- c("storm_surge3_high")

storm_surge3_highflood <- storm_surge3_high %>%
  mutate(Flood = ifelse(storm_surge3_high > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n)

storm_surge3_highprop <- round(prop.table(as.matrix(storm_surge3_highflood), 1), 3)

#there is a 57.2% chance of flooding under these conditions
```

```{r}
# Counting the amount of floods and proportions with a storm surge of 2m at low tide

storm_surge3_low <- rnorm(10000, mean = 3, sd = 3) %>%
  as.data.frame

colnames(storm_surge3_low) <- c("storm_surge3_low")

storm_surge3_lowflood <- storm_surge3_low %>%
  mutate(Flood = ifelse(storm_surge3_low > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n)

storm_surge3_lowprop <- round(prop.table(as.matrix(storm_surge3_lowflood), 1), 3)

#there is a 6.8% chance of flooding under these conditions
```

```{r}
#Create table of probability of flooding

flood_probability_select <- flooding_probability %>%
  select(-conditions) #created a data frame without the column conditions

rownames(flood_probability_select) <- c("Normal Conditions", "Storm Surge 1m", "Storm Surge 2m", "Storm Surge 3m") #set the row names in the data frame as what the conditions were

flood_probability_table <- kable(flood_probability_select,
                                 col.names = c("Low Tide", "Mid Tide", "High Tide"),
                                 caption = "Table 1. Risk of Flooding in New York at Low, Mid and High Tide, Under Normal Conditions and Storm Surges of 1m, 2m, and 3m"
                                  ) %>%
  kable_styling(bootstrap_options = c("striped"), full_width = FALSE)

flood_probability_table

```

Part 2 Factoring in Climate Change

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 10 percentile sea level rise or 7 inches/ 0.1778m at high tide

flood_risk_ht_2050 <- rnorm(10000, mean = 5.1778, sd = 3) %>%
  as.data.frame

colnames(flood_risk_ht_2050) <- c("flood_risk_ht_2050")

flood_risk_ht_2050_t10 <- flood_risk_ht_2050 %>%
  mutate(Flood = ifelse(flood_risk_ht_2050 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

flood_risk_ht_2050_prop <- round(prop.table(as.matrix(flood_risk_ht_2050_t), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 10 percentile sea level rise or 7 inches/ 0.1778m at mid tide

flood_risk_mt_2050 <- rnorm(10000, mean = 2.6778, sd = 3) %>%
  as.data.frame

colnames(flood_risk_mt_2050) <- c("flood_risk_mt_2050")

flood_risk_mt_2050_t10 <- flood_risk_mt_2050 %>%
  mutate(Flood = ifelse(flood_risk_mt_2050 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

flood_risk_mt_2050_prop10 <- round(prop.table(as.matrix(flood_risk_mt_2050_t10), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 10 percentile sea level rise or 7 inches/ 0.1778m at mid tide

flood_risk_lt_2050 <- rnorm(10000, mean = 0.1778, sd = 3) %>%
  as.data.frame

colnames(flood_risk_lt_2050) <- c("flood_risk_lt_2050")

flood_risk_lt_2050_t10 <- flood_risk_lt_2050 %>%
  mutate(Flood = ifelse(flood_risk_lt_2050 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

flood_risk_lt_2050_prop10 <- round(prop.table(as.matrix(flood_risk_lt_2050_t10), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods
```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 90 percentile sea level rise or 7 inches/ 0.7874m at high tide

flood_risk_ht_2050_90 <- rnorm(10000, mean = 5.7874, sd = 3) %>%
  as.data.frame

colnames(flood_risk_ht_2050_90) <- c("flood_risk_ht_2050_90")

flood_risk_ht_2050_t90 <- flood_risk_ht_2050_90 %>%
  mutate(Flood = ifelse(flood_risk_ht_2050_90 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

flood_risk_ht_2050_prop90 <- round(prop.table(as.matrix(flood_risk_ht_2050_t90), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 90 percentile sea level rise or 31 inches/ 0.7874m at mid tide

flood_risk_mt_2050_90 <- rnorm(10000, mean = 3.2874, sd = 3) %>%
  as.data.frame

colnames(flood_risk_mt_2050_90) <- c("flood_risk_mt_2050_90")

flood_risk_mt_2050_t90 <- flood_risk_mt_2050_90 %>%
  mutate(Flood = ifelse(flood_risk_mt_2050_90 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

flood_risk_mt_2050_prop90 <- round(prop.table(as.matrix(flood_risk_mt_2050_t90), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 90 percentile sea level rise or 7 inches/ 0.7874m at mid tide

flood_risk_lt_2050_90 <- rnorm(10000, mean = 0.7874, sd = 3) %>%
  as.data.frame

colnames(flood_risk_lt_2050_90) <- c("flood_risk_lt_2050_90")

flood_risk_lt_2050_t90 <- flood_risk_lt_2050_90 %>%
  mutate(Flood = ifelse(flood_risk_lt_2050_90 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

flood_risk_lt_2050_prop90 <- round(prop.table(as.matrix(flood_risk_lt_2050_t90), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods
```





Storm surge 1m
```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 10 percentile sea level rise or 7 inches/ 0.1778m at high tide
#storm surge 1 m

flood_risk_ht_2050_s1 <- rnorm(10000, mean = 6.1778, sd = 3) %>%
  as.data.frame

colnames(flood_risk_ht_2050_s1) <- c("flood_risk_ht_2050_s1")

s1_flood_risk_ht_2050_t10 <- flood_risk_ht_2050_s1 %>%
  mutate(Flood = ifelse(flood_risk_ht_2050_s1 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

s1_flood_risk_ht_2050_prop <- round(prop.table(as.matrix(s1_flood_risk_ht_2050_t10), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 10 percentile sea level rise or 7 inches/ 0.1778m at mid tide
#storm surge 1m

flood_risk_mt_2050_s1 <- rnorm(10000, mean = 3.6778, sd = 3) %>%
  as.data.frame

colnames(flood_risk_mt_2050_s1) <- c("flood_risk_mt_2050_s1")

s1_flood_risk_mt_2050_t10 <- flood_risk_mt_2050_s1 %>%
  mutate(Flood = ifelse(flood_risk_mt_2050_s1 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

s1_flood_risk_mt_2050_prop10 <- round(prop.table(as.matrix(s1_flood_risk_mt_2050_t10), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 10 percentile sea level rise or 7 inches/ 0.1778m at mid tide
#storm surge 1m

flood_risk_lt_2050_s1 <- rnorm(10000, mean = 1.1778, sd = 3) %>%
  as.data.frame

colnames(flood_risk_lt_2050_s1) <- c("flood_risk_lt_2050_s1")

s1_flood_risk_lt_2050_t10 <- flood_risk_lt_2050_s1 %>%
  mutate(Flood = ifelse(flood_risk_lt_2050_s1 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

s1_flood_risk_lt_2050_prop10 <- round(prop.table(as.matrix(s1_flood_risk_lt_2050_t10), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods
```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 90 percentile sea level rise or 7 inches/ 0.7874m at high tide
# Storm Surge 1m
flood_risk_ht_2050_90_s1 <- rnorm(10000, mean = 6.7874, sd = 3) %>%
  as.data.frame

colnames(flood_risk_ht_2050_90_s1) <- c("flood_risk_ht_2050_90_s1")

s1_flood_risk_ht_2050_t90 <- flood_risk_ht_2050_90_s1 %>%
  mutate(Flood = ifelse(flood_risk_ht_2050_90_s1 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

s1_flood_risk_ht_2050_prop90 <- round(prop.table(as.matrix(s1_flood_risk_ht_2050_t90), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 90 percentile sea level rise or 31 inches/ 0.7874m at mid tide

flood_risk_mt_2050_90_s1 <- rnorm(10000, mean = 4.2874, sd = 3) %>%
  as.data.frame

colnames(flood_risk_mt_2050_90_s1) <- c("flood_risk_mt_2050_90_s1")

s1_flood_risk_mt_2050_t90 <- flood_risk_mt_2050_90_s1 %>%
  mutate(Flood = ifelse(flood_risk_mt_2050_90_s1 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

s1_flood_risk_mt_2050_prop90 <- round(prop.table(as.matrix(s1_flood_risk_mt_2050_t90), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 90 percentile sea level rise or 7 inches/ 0.7874m at mid tide

flood_risk_lt_2050_90_s1 <- rnorm(10000, mean = 1.7874, sd = 3) %>%
  as.data.frame

colnames(flood_risk_lt_2050_90_s1) <- c("flood_risk_lt_2050_90_s1")

s1_flood_risk_lt_2050_t90 <- flood_risk_lt_2050_90_s1 %>%
  mutate(Flood = ifelse(flood_risk_lt_2050_90_s1 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

s1_flood_risk_lt_2050_prop90 <- round(prop.table(as.matrix(s1_flood_risk_lt_2050_t90), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods
```






Storm Surge 2m
```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 10 percentile sea level rise or 7 inches/ 0.1778m at high tide
#storm surge 2 m

flood_risk_ht_2050_s2 <- rnorm(10000, mean = 7.1778, sd = 3) %>%
  as.data.frame

colnames(flood_risk_ht_2050_s2) <- c("flood_risk_ht_2050_s2")

s2_flood_risk_ht_2050_t10 <- flood_risk_ht_2050_s2 %>%
  mutate(Flood = ifelse(flood_risk_ht_2050_s2 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

surge2_fr_ht_2050_prop10 <- round(prop.table(as.matrix(s2_flood_risk_ht_2050_t10), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 10 percentile sea level rise or 7 inches/ 0.1778m at mid tide
#storm surge 1m

flood_risk_mt_2050_s2 <- rnorm(10000, mean = 4.6778, sd = 3) %>%
  as.data.frame

colnames(flood_risk_mt_2050_s2) <- c("flood_risk_mt_2050_s2")

s2_flood_risk_mt_2050_t10 <- flood_risk_mt_2050_s2 %>%
  mutate(Flood = ifelse(flood_risk_mt_2050_s2 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

surge2_fr_mt_2050_prop10 <- round(prop.table(as.matrix(s2_flood_risk_mt_2050_t10), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 10 percentile sea level rise or 7 inches/ 0.1778m at mid tide
#storm surge 2m

flood_risk_lt_2050_s2 <- rnorm(10000, mean = 2.1778, sd = 3) %>%
  as.data.frame

colnames(flood_risk_lt_2050_s2) <- c("flood_risk_lt_2050_s2")

s2_flood_risk_lt_2050_t10 <- flood_risk_lt_2050_s2 %>%
  mutate(Flood = ifelse(flood_risk_lt_2050_s2 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

surge2_fr_lt_2050_prop10 <- round(prop.table(as.matrix(s2_flood_risk_lt_2050_t10), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods
```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 90 percentile sea level rise or 7 inches/ 0.7874m at high tide
# Storm Surge 1m
flood_risk_ht_2050_90_s2 <- rnorm(10000, mean = 7.7874, sd = 3) %>%
  as.data.frame

colnames(flood_risk_ht_2050_90_s2) <- c("flood_risk_ht_2050_90_s2")

s2_flood_risk_ht_2050_t90 <- flood_risk_ht_2050_90_s2 %>%
  mutate(Flood = ifelse(flood_risk_ht_2050_90_s2 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

surge2_fr_ht_2050_prop90 <- round(prop.table(as.matrix(s2_flood_risk_ht_2050_t90), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 90 percentile sea level rise or 31 inches/ 0.7874m at mid tide

flood_risk_mt_2050_90_s2 <- rnorm(10000, mean = 5.2874, sd = 3) %>%
  as.data.frame

colnames(flood_risk_mt_2050_90_s2) <- c("flood_risk_mt_2050_90_s2")

s2_flood_risk_mt_2050_t90 <- flood_risk_mt_2050_90_s2 %>%
  mutate(Flood = ifelse(flood_risk_mt_2050_90_s2 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

surge2_fr_mt_2050_prop90 <- round(prop.table(as.matrix(s2_flood_risk_mt_2050_t90), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 90 percentile sea level rise or 7 inches/ 0.7874m at mid tide

flood_risk_lt_2050_90_s2 <- rnorm(10000, mean = 2.7874, sd = 3) %>%
  as.data.frame

colnames(flood_risk_lt_2050_90_s2) <- c("flood_risk_lt_2050_90_s2")

s2_flood_risk_lt_2050_t90 <- flood_risk_lt_2050_90_s2 %>%
  mutate(Flood = ifelse(flood_risk_lt_2050_90_s2 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

surge2_fr_lt_2050_prop90 <- round(prop.table(as.matrix(s2_flood_risk_lt_2050_t90), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods
```






Storm Surge 3m
```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 10 percentile sea level rise or 7 inches/ 0.1778m at high tide
#storm surge 3 m

flood_risk_ht_2050_s3 <- rnorm(10000, mean = 8.1778, sd = 3) %>%
  as.data.frame

colnames(flood_risk_ht_2050_s3) <- c("flood_risk_ht_2050_s3")

s3_flood_risk_ht_2050_t10 <- flood_risk_ht_2050_s3 %>%
  mutate(Flood = ifelse(flood_risk_ht_2050_s3 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

storm3m_fr_ht_2050_prop10 <- round(prop.table(as.matrix(s3_flood_risk_ht_2050_t10), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 10 percentile sea level rise or 7 inches/ 0.1778m at mid tide
#storm surge 1m

flood_risk_mt_2050_s3 <- rnorm(10000, mean = 5.6778, sd = 3) %>%
  as.data.frame

colnames(flood_risk_mt_2050_s3) <- c("flood_risk_mt_2050_s3")

s3_flood_risk_mt_2050_t10 <- flood_risk_mt_2050_s3 %>%
  mutate(Flood = ifelse(flood_risk_mt_2050_s3 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

storm3m_fr_mt_2050_prop10 <- round(prop.table(as.matrix(s3_flood_risk_mt_2050_t10), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 10 percentile sea level rise or 7 inches/ 0.1778m at mid tide
#storm surge 2m

flood_risk_lt_2050_s3 <- rnorm(10000, mean = 3.1778, sd = 3) %>%
  as.data.frame

colnames(flood_risk_lt_2050_s3) <- c("flood_risk_lt_2050_s3")

s3_flood_risk_lt_2050_t10 <- flood_risk_lt_2050_s3 %>%
  mutate(Flood = ifelse(flood_risk_lt_2050_s3 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

storm3m_fr_lt_2050_prop10 <- round(prop.table(as.matrix(s3_flood_risk_lt_2050_t10), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods
```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 90 percentile sea level rise or 7 inches/ 0.7874m at high tide
# Storm Surge 1m
flood_risk_ht_2050_90_s3 <- rnorm(10000, mean = 8.7874, sd = 3) %>%
  as.data.frame

colnames(flood_risk_ht_2050_90_s3) <- c("flood_risk_ht_2050_90_s3")

s3_flood_risk_ht_2050_t90 <- flood_risk_ht_2050_90_s3 %>%
  mutate(Flood = ifelse(flood_risk_ht_2050_90_s3 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

storm3m_fr_ht_2050_prop90 <- round(prop.table(as.matrix(s3_flood_risk_ht_2050_t90), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 90 percentile sea level rise or 31 inches/ 0.7874m at mid tide

flood_risk_mt_2050_90_s3 <- rnorm(10000, mean = 6.2874, sd = 3) %>%
  as.data.frame

colnames(flood_risk_mt_2050_90_s3) <- c("flood_risk_mt_2050_90_s3")

s3_flood_risk_mt_2050_t90 <- flood_risk_mt_2050_90_s3 %>%
  mutate(Flood = ifelse(flood_risk_mt_2050_90_s3 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

storm3m_fr_mt_2050_prop90 <- round(prop.table(as.matrix(s3_flood_risk_mt_2050_t90), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods

```

```{r}
# Estimating the change in flood risk as sea level rises in 2050
# 90 percentile sea level rise or 7 inches/ 0.7874m at mid tide

flood_risk_lt_2050_90_s3 <- rnorm(10000, mean = 3.7874, sd = 3) %>%
  as.data.frame

colnames(flood_risk_lt_2050_90_s3) <- c("flood_risk_lt_2050_90_s2")

s3_flood_risk_lt_2050_t90 <- flood_risk_lt_2050_90_s3 %>%
  mutate(Flood = ifelse(flood_risk_lt_2050_90_s3 > 7.5, "Flood", "No Flood")) %>%
  count(Flood, Flood) %>%
  spread(Flood, n) # Creating a count of the number of time that the water is high enough to flood assuming over 7.5 m causes a significant flood.

storm3m_fr_lt_2050_prop90 <- round(prop.table(as.matrix(s3_flood_risk_lt_2050_t90), 1), 3) #Creates a proportion table of the number of floods vs the number of no floods
```




Creating table from flood risk 2050 data



